### ISSUE TITLE
Download & Upload Grade 10 Past Papers

### ISSUE THREAD

**Issue by KgotsoKP** [deltaCS99/resource#21]
***Note*** : The order in which the following are done does not matter

**TODO**

Mathematics
- [x] Download Grade 10 Maths past papers
- [ ] Upload Grade 10 Maths past papers 

Physical Sciences
- [ ] Download Grade 10 Physics past papers
- [ ] Upload Grade 10 Physics papers

**Comment by KgotsoKP** [comment]
- Can be tracked in Nontion or Excel
