### ISSUE TITLE
Download & upload grade 11 Past Papers

### ISSUE THREAD

**Issue by KgotsoKP** [deltaCS99/resource#22]
***Note*** : The order in which the following are done does not matter

**TODO**

Mathematics
- [x] Download Grade 11 Maths past papers
- [ ] Upload Grade 11 Maths past papers 

Physical Sciences
- [ ] Download Grade 11 Physics past papers
- [ ] Upload Grade 11 Physics papers

**Comment by KgotsoKP** [comment]
- Can be tracked in notion or excel
