### ISSUE TITLE
Join the community section

### ISSUE THREAD

**Issue by KgotsoKP** [deltaCS99/resource#23]
**What is it**
- The purpose of this feature is to encourage users to follow/join our social platforms.

**Why do we need it/ Benefits**
-  Whenever there is a new feature/service it easy to announce it to relevant audience.
- This will also help in terms of gathering feedback on anything our users use , it will be a way to invite them to provide feedback

**TODO**
- [x] Set up all social accounts 
- [x] Set up whatsapp community
- [x] Set up WhatsApp general information 
- [x] Set up Youtube channels ( Grade 10 , 11 & 12)
- [x] Implement desktop design
- [x] Implement tablet design
- [x] Implement mobile design

**Design Files**
- Provided in the figma file
