### ISSUE TITLE
Material Navbar

### ISSUE THREAD

**Issue by KgotsoKP** [deltaCS99/resource#25]
**What is it**
Nav bar for selecting grade and subjects

**TODO**
- [x] jsx styling -> modular css
- [x] Fix selectors colour and padding

**When we have time**
- [ ] custom design dropdown
- [ ] make dropdown a bottom sheet on mobile

**Design***
- provided in figma file
